cannavase/cannavase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
#Imports Extras
import debug_toolbar
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),
    
    #Admin-User Paths
    # url(r'^login/$',auth_views.LoginView.as_view(template_name="utils/login.html"), name="login"),
    # url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    #path('novedades/', include('novedades.urls')),
    path('noticias/', include('noticias.urls')),

    #SISTEMA
    path('operadores/', include('operadores.urls')),
    path('georef/', include('georef.urls')),
    path('inventario/', include('inventario.urls')),
    path('produccion/', include('produccion.urls')),
    path('comercial/', include('comercial.urls')),
    path('reportes/', include('reportes.urls')),
    # path('laboratorio/', include('laboratorio.urls')),
    path('cultivo/', include('cultivo.urls')),

    #API
    path('api/', include('georef.urlsAPI')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cannavase/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete
#Definimos nuestros Paths

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('cooperamos', views.cooperamos, name='cooperamos'),
    path('hacemos', views.hacemos, name='hacemos'),
    path('somos', views.somos, name='somos'),
    path('contactos', views.contactos, name='contactos'),

    path('menu', views.menu, name='menu'),

    path('mostrar', views.mostrar, name='mostrar'),

    path('menu_opciones', views.menu_opciones, name='menu_opciones'),
    path('alianzas', views.lista_alianzas, name='lista_alianzas'),
    path('alianzas/crear', views.cargar_alianza, name='crear_alianza'),
    path('alianzas/mod/<int:alianza_id>', views.cargar_alianza, name='modificar_alianza'),
    path('alianzas/del/<int:alianza_id>', views.desactivar_alianza, name='desactivar_alianza'),
    path('directivos', views.lista_directivos, name='lista_directivos'),
    path('directivos/crear', views.cargar_directivo, name='crear_directivo'),
    path('directivos/mod/<int:directivo_id>', views.cargar_directivo, name='modificar_directivo'),
    path('directivos/del/<int:directivo_id>', views.desactivar_directivo, name='desactivar_directivo'),
    path('videos', views.lista_videos, name='lista_videos'),
    path('videos/crear', views.cargar_video, name='cargar_video'),
    path('videos/mod/<int:video_id>', views.cargar_video, name='modificar_video'),
    path('videos/del/<int:video_id>', views.desactivar_video, name='desactivar_video'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    path('construccion', views.construccion, name='construccion'),
]

cannavase/inventario/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#imports extra
from dal import autocomplete
#Import de modulos personales
from . import views
from . import autocomplete

#Definimos los paths de la app
app_name = 'inventario'
urlpatterns = [
    path('', views.menu, name='menu'),
    #Rubro:
    path('crear/rubro', views.crear_rubro, name='crear_rubro'),
    path('mod/rubro/<int:rubro_id>', views.crear_rubro, name='mod_rubro'),
    #Basico Items
    path('lista', views.lista_items, name='lista_items'),
    path('ver/<int:item_id>', views.ver_item, name='ver_item'),
    path('crear', views.crear_item, name='crear_item'),
    path('mod/<int:item_id>', views.crear_item, name='mod_item'),
    path('clonar/<int:item_id>', views.clonar_item, name='clonar_item'),
    path('del/<int:item_id>', views.eliminar_item, name='eliminar_item'),
    #caracteristica
    path('crear/caracteristica/<int:item_id>', views.cargar_caracteristica, name='cargar_caracteristica'),
    path('mod/caracteristica/<int:caracteristica_id>', views.cargar_caracteristica, name='mod_caracteristica'),
    #eventos:
    path('crear/evento/<int:item_id>', views.crear_evento, name='crear_evento'),
    path('devolver/<int:evento_id>', views.devolver_item, name='devolver'),
    path('transferir/<int:item_id>', views.transferir_item, name='transferir_item'),
    path('del/evento/<int:evento_id>', views.del_evento, name='del_evento'),

    #Reportes
    path('stock_semillas', views.stock_semillas, name='stock_semillas'),

    #Semillas
    path('menu_semillas', views.menu_semillas, name='menu_semillas'),
    path('lista_semillas', views.lista_semillas, name='lista_semillas'),
    path('cargar_semillas', views.crear_semilla, name='cargar_semillas'),
    path('mod_semillas/<int:semilla_id>', views.cargar_semilla, name='mod_semillas'),
    path('detalle_semilla/<int:semilla_id>', views.detalle_semilla, name='detalle_semilla'),
    path('baja_semilla/<int:semilla_id>', views.baja_semilla, name='baja_semilla'),

    #Semillas (Almacenes)
    path('p/stock_semillas', views.p_stock_semillas, name='p_stock_semillas'),
    path('p/stock_ingresar', views.ingreso, name='p_stock_ingresar'),
    path('p/stock_detalles/<int:stock_id>', views.detalle_stock, name='p_stock_detalles'),
    path('p/stock_mod/<int:stock_id>', views.mod_stock, name='p_stock_mod'),
    path('p/stock_baja/<int:stock_id>', views.baja_stock, name='p_stock_baja'),

    #Autocomplete
    url(r'^rubros-autocomplete/$', autocomplete.RubrosAutocomplete.as_view(), name='rubros-autocomplete',),
    url(r'^items-autocomplete/$', autocomplete.ItemsAutocomplete.as_view(), name='items-autocomplete',),
]

cannavase/produccion/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#imports extra
from dal import autocomplete
#Import de modulos personales
from . import views
from . import autocomplete

#Definimos los paths de la app
app_name = 'produccion'
urlpatterns = [
    path('', views.menu, name='menu'),
    #Lotes:
    path('lista/<str:tipo>', views.lista_objetos, name='lista_objetos'),
    path('lista_germinacion/<str:tipo>', views.lista_germinacion, name='lista_germinacion'),
    path('lista_vegetacion/<str:tipo>', views.lista_vegetacion, name='lista_vegetacion'),
    path('lista_floracion/<str:tipo>', views.lista_floracion, name='lista_floracion'),
    path('lista_cosecha/<str:tipo>', views.lista_cosecha, name='lista_cosecha'),
    path('lista_finalizados/<str:tipo>', views.lista_finalizados, name='lista_finalizados'),
    path('ver/<int:objeto_id>', views.ver_objeto, name='ver_objeto'),
    path('mod/<int:objeto_id>', views.mod_objeto, name='mod_objeto'),
    #acciones
    path('germinar/<int:semilla_id>', views.germinar, name='germinar'),
    path('agregar/semillas/<int:objeto_id>', views.agregar_semillas, name='agregar_semillas'),
    path('aplicar/<int:objeto_id>', views.aplicar_insumo, name='aplicar_insumo'),
    path('regar/<int:objeto_id>', views.regar, name='regar'),
    path('evolucionar/<int:objeto_id>', views.evolucionar_objeto, name='evolucionar_objeto'),
    path('individualizar/<int:objeto_id>', views.individualizar, name='individualizar'),
    path('individualizar/<int:objeto_id>/ubicacion/<int:ubicacion_id>', views.individualizar, name='individualizar_ubicacion'),
    path('transplantar/<int:objeto_id>', views.trasplantar, name='trasplantar'),
    path('trasplantar/ubicacion/<int:ubicacion_id>', views.trasplantar_ubicacion, name='trasplantar_ubicacion'),
    path('eliminar/<int:objeto_id>', views.eliminar_objeto, name='eliminar_objeto'),
    path('eliminar/ubicacion/<int:ubicacion_id>', views.del_ubicacion, name='del_ubicacion'),
    path('eliminar/accion/<int:accion_id>', views.del_accion, name='del_accion'),
    #caracteristicas
    path('crear/caracteristica/<int:objeto_id>', views.cargar_caracteristica, name='cargar_caracteristica'),
    path('mod/caracteristica/<int:caracteristica_id>', views.cargar_caracteristica, name='mod_caracteristica'),
    #REPORTES
    path('rep/lotes/semb', views.lotes_sembrados, name='lotes_sembrados'),
    path('rep/lotes/veg', views.lotes_vegetativos, name='lotes_vegetativos'),
    path('rep/lotes/flo', views.lotes_floracion, name='lotes_floracion'),
    path('rep/lotes/sec', views.lotes_secado, name='lotes_secado'),
    path('rep/bajas', views.plantas_eliminadas, name='plantas_eliminadas'),
    #Autocompletes
    url(r'^lotes-autocomplete/$', autocomplete.LotesAutocomplete.as_view(), name='lotes-autocomplete',),
    url(r'^plantas-autocomplete/$', autocomplete.PlantasAutocomplete.as_view(), name='plantas-autocomplete',),
]

cannavase/inventario/models.py
#Import standard de Djagno
from django.db import models
from django.utils import timezone
#Import Extras
from tinymce.models import HTMLField
from auditlog.registry import auditlog
#Imports del proyecto
from cannavase.settings import LOADDATA
from core.choices import TIPO_MEDIDA
from operadores.models import Operador
from georef.models import Ubicacion
from georef.choices import TIPO_UBICACION
from produccion.choices import TIPO_ENVASE
from comercial.models import Proveedor
#Imports de la app
from .choices import TIPO_ITEM, TIPO_CARACTERISTICA, TIPO_EVENTO_ITEM, SEXO

# Create your models here.
class Rubro(models.Model):
    nombre = models.CharField('Nombre', max_length=200)
    class Meta:
        ordering = ['nombre', ]
    def __str__(self):
        return self.nombre

class Item(models.Model):
    rubro = models.ForeignKey(Rubro, on_delete=models.CASCADE, related_name="items")
    tipo = models.CharField('Tipo', max_length=3 ,choices=TIPO_ITEM, default='SAC')
    origen = models.ForeignKey(Proveedor, on_delete=models.CASCADE, related_name="items")
    nombre = models.CharField('Nombre', max_length=200)
    identificador = models.CharField('identificador', max_length=50, null=True, blank=True)
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE, related_name="items")
    detalle = models.CharField('detalle', max_length=400, null=True, blank=True)
    cantidad = models.DecimalField('Cantidad Inicial', max_digits=10, decimal_places=3, default=0)
    medida = models.CharField('Tipo', max_length=3 ,choices=TIPO_MEDIDA, default='GR')
    responsable = models.ForeignKey(Operador, on_delete=models.CASCADE, related_name="items")
    class Meta:
        ordering = ['rubro', 'nombre', ]
        unique_together = ['tipo', 'identificador']
    def __str__(self):
        return self.nombre + ": " + str(self.identificador)
    def creacion(self):
        origenes = [e for e in self.eventos.all() if e.accion=="O"]
        if origenes:
            return origenes[0]
    def cantidad_distribuida(self):
        return sum([e.cantidad for e in self.eventos.all() if e.accion=="R"])
    def cantidad_disponible(self):
        #No tener en cuenta la accion inicial
        return self.cantidad + sum([e.cantidad for e in self.eventos.all() if e.accion=="I"]) - sum([e.cantidad for e in self.eventos.all() if e.accion=="R"])

class CaracteristicaItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="caracteristicas")
    tipo = models.CharField('Tipo', max_length=3 ,choices=TIPO_CARACTERISTICA, default='')
    valor = models.DecimalField('valor', max_digits=8, decimal_places=4, default=0)
    medida = models.CharField('Medida', max_length=3 ,choices=TIPO_MEDIDA, default='THC')
    aclaracion = models.CharField('aclaracion', max_length=200, null=True, blank=True)

class EventoItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="eventos")
    accion = models.CharField('Accion', max_length=1 ,choices=TIPO_EVENTO_ITEM, default='I')
    cantidad = models.DecimalField('Cantidad', max_digits=10, decimal_places=3, default=0)
    aclaracion = models.CharField('aclaracion', max_length=400)
    fecha = models.DateTimeField('Fecha del evento', default=timezone.now)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE, related_name="eventositems")
    def __str__(self):
        return str(self.item) + ' (' + self.get_accion_display() + ": " + str(self.cantidad) + self.item.get_medida_display() + ")"

# Modelos para la nueva seccion de Semillas
class Proveedor(models.Model):
    nombre = models.CharField('Nombre', max_length=60)
    observaciones = models.CharField('Observaciones', max_length=400)
    def __str__(self):
        return str(self.nombre)

#Clases para seccion Semillas
class Variedad(models.Model):
    raza = models.CharField('Raza', max_length=100)
    origen = models.ForeignKey(Proveedor, on_delete=models.CASCADE, related_name='proveedores')
    poder_germinativo = models.DecimalField('Poder Germinativo', decimal_places=3, max_digits=10)
    thc = models.DecimalField('THC', decimal_places=3, max_digits=10)
    cbd = models.DecimalField('CBD', decimal_places=3, max_digits=10)
    morfologia = models.CharField('Morfología', max_length=100)
    sexo = models.CharField('Sexo', max_length=1, choices=SEXO, default='M')
    genotipo = models.CharField('Genotipo', max_length=100)
    dias_floracion = models.IntegerField('Dias de Floración')
    rendimiento = models.DecimalField('Rendimiento Esperado', decimal_places=3, max_digits=10)
    altura = models.DecimalField('Altura promedio', decimal_places=3, max_digits=10)
    observaciones = models.CharField('Observaciones', max_length=400)
    fecha_importacion = models.DateField('Fecha de Importación', default=timezone.now)
    fecha_carga = models.DateField('Fecha de Carga', default=timezone.now)
    activo = models.BooleanField('Activo', default=True)
    def __str__(self):
        return self.raza


class Almacen(models.Model):
    variedad = models.ForeignKey(Variedad, on_delete=models.CASCADE, related_name='variedades')
    codigo = models.CharField('Código del Paquete', max_length=100)
    cant_semillas = models.IntegerField('Cantidad de Semillas')
    peso = models.DecimalField('Peso en Gramos', decimal_places=3, max_digits=10)
    peso_utilizado = models.DecimalField('Peso Utilizado', decimal_places=3, max_digits=10, default=0)
    peso_disponible = models.DecimalField('Peso Disponible', decimal_places=3, max_digits=10, default=0)
    tipo_envase = models.CharField('Tipo de Envase', choices=TIPO_ENVASE, max_length=3)
    sububicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE)
    certificado_importacion = models.ImageField(upload_to='../archivos/certificados/')
    observaciones = HTMLField()
    contenedor = models.CharField('Tipo de Contenedor', choices=TIPO_UBICACION, max_length=3)
    certificado_tecnico = models.ImageField(upload_to='../archivos/cetificados/')
    fecha_alta = models.DateField('Fecha de Alta', default=timezone.now)
    fecha_carga = models.DateField('Fecha de Carga', default=timezone.now)
    activo = models.BooleanField('Activo', default=True)



if not LOADDATA:
    #Auditoria
    auditlog.register(Item)
    auditlog.register(EventoItem)

cannavase/inventario/forms.py
#Imports Python
#Imports Django
from django import forms
#Imports extra
from dal import autocomplete
from tinymce.widgets import TinyMCE
#Imports del proyecto
#Imports de la app
from .models import Rubro
from .models import Item, CaracteristicaItem, EventoItem
from .models import Proveedor
from .models import Variedad, Almacen

#Definimos nuestros forms
class RubroForm(forms.ModelForm):
    class Meta:
        model = Rubro
        fields= '__all__'

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        widgets = {
            'responsable' : autocomplete.ModelSelect2(url='operadores:operadores-autocomplete'),
        }

class SemillaForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        exclude = ('rubro', 'tipo',)
        widgets = {
            'responsable': autocomplete.ModelSelect2(url='operadores:operadores-autocomplete'),
        }

class CaracteristicaItemForm(forms.ModelForm):
    class Meta:
        model = CaracteristicaItem
        fields= '__all__'
        exclude = ('item', )

class ModItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields= '__all__'
        widgets = {
            'responsable' : autocomplete.ModelSelect2(url='operadores:operadores-autocomplete'),
        }

class EventoItemForm(forms.ModelForm):
    class Meta:
        model = EventoItem
        fields= '__all__'
        exclude = ('item', 'fecha', )
        widgets = {
            'operador' : autocomplete.ModelSelect2(url='operadores:operadores-autocomplete'),
        }

class TransferirForm(forms.Form):
    destino = forms.ModelChoiceField(
        queryset=Item.objects.all(),
        widget=autocomplete.ModelSelect2(url='inventario:items-autocomplete'),
        required=True,
    )
    cantidad = forms.DecimalField(label="Cantidad")
    aclaracion = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))


class VariedadForm(forms.ModelForm):
    class Meta:
        model = Variedad
        fields = '__all__'
        exclude = ('activo',)


class AlmacenForm(forms.ModelForm):
    class Meta:
        model = Almacen
        fields = '__all__'
        exclude = ('peso_disponible', 'peso_utilizado', 'activo',)

cannavase/inventario/templates/semillas/detalle_semillas.html
{% extends 'base_inventario.html' %}

{% load static %}

{% block body_block %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Detalle de Semilla:</h2>
        </div>
        <div class="row">
        <div class="col-md-8">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Raza</th>
                        <td>{{semilla.raza}}</td>
                    </tr>
                    <tr>
                        <th>Origen</th>
                        <td>{{semilla.origen}}</td>
                    </tr>
                    <tr>
                        <th>Poder Germinativo</th>
                        <td>{{semilla.poder_germinativo}}</td>
                    </tr>
                    <tr>
                        <th>THC</th>
                        <td>{{semilla.thc}}</td>
                    </tr>
                    <tr>
                        <th>CBD</th>
                        <td>{{semilla.cbd}}</td>
                    </tr>
                    <tr>
                        <th>Morfología</th>
                        <td>{{semilla.morfologia}}</td>
                    </tr>
                    <tr>
                        <th>Sexo</th>
                        <td>{{semilla.sexo}}</td>
                    </tr>
                    <tr>
                        <th>Genotipo</th>
                        <td>{{semilla.genotipo}}</td>
                    </tr>
                    <tr>
                        <th>Dias de Floración</th>
                        <td>{{semilla.dias_floracion}}</td>
                    </tr>
                    <tr>
                        <th>Rendimiento Esperado</th>
                        <td>{{semilla.rendimiento}}</td>
                    </tr>
                    <tr>
                        <th>Altura Promedio</th>
                        <td>{{semilla.altura}}</td>
                    </tr>
                    <tr>
                        <th>Observaciones</th>
                        <td>{{semilla.observaciones}}</td>
                    </tr>
                    <tr>
                        <th>Fecha de Importación</th>
                        <td>{{semilla.fecha_importacion}}</td>
                    </tr>
                    <tr>
                        <th>Fecha de carga</th>
                        <td>{{semilla.fecha_carga}}</td>
                    </tr>
                </thead>
            </table>
        </div>
    </div><br>
    <div><a class="btn btn-primary btn-sm float-right" href="{% url 'inventario:lista_semillas' %}">Volver al Listado</a></div>
{% endblock %}

cannavase/inventario/templates/semillas/lista_semillas.html
{% extends 'base_inventario.html' %}

{% load static %}

{% block body_block %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Listado de Semillas</h2>
            <a class="botoncito" href="{% url 'inventario:cargar_semillas' %}">
                Ingresar Semilla
               <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Ingresar">
            </a><br>
            <a class="btn btn-primary btn-sm float-right" href="{% url 'core:menu' %}">Volver al Menú</a>
        </div>
        <div class="row">
        <div class="col-md-12">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Rubro</th>
                        <th>Nombre</th>
                        <th>Identificador</th>
                        <th>Cantidad Utilizada</th>
                        <th>Cantidad Disponible</th>
                        <th>Administrador</th>
                        <th>Ver Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                        {% if item.cantidad_disponible > 0 %}
                            <tr>
                                <td>{{item.rubro}}</td>
                                <td>{{item.nombre}}</td>
                                <td>{{item.identificador}}</td>
                                <td>{{item.cantidad_distribuida}}{{item.get_medida_display}}</td>
                                {% if item.cantidad_disponible > 0 %}
                                <td style="color: green;">{{item.cantidad_disponible}}{{item.get_medida_display}}</td>
                                {% else %}
                                <td style="color: red;">{{item.cantidad_disponible}}{{item.get_medida_display}}</td>
                                {% endif %}
                                <td>{{item.responsable}}</td>
                                <td>
                                    <a href="{% url 'inventario:ver_item' item_id=item.id %}">
                                        <img class="icons" src="{% static '/img/icons/ver.png' %}">
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

cannavase/inventario/templates/semillas/menu_semillas.html
{% extends 'base_inventario.html' %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu Semillas:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            {% if perms.operadores.inventario_admin %}
                                <li><a href="{% url 'inventario:lista_semillas' %}">Variedades</a></li>
                                <li><a href="{% url 'inventario:stock_semillas' %}">Almacenes</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        {% include 'info_user.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

cannavase/inventario/templates/semillas/stock_semillas.html
{% extends 'base_inventario.html' %}

{% load static %}

{% block body_block %}
<style>
    .ref {
        border-top-width: 3px;
        border-right-width: 3px;
        border-bottom-width: 3px;
        border-left-width: 3px;
        border-top-style: dotted;
        border-right-style: dotted;
        border-bottom-style: dotted;
        border-left-style: dotted;
        border-top-color: green;
        border-right-color: green;
        border-bottom-color: green;
        border-left-color: green;
    }
</style>

    <div class="beneficiario container">
        <div class="row">
            <div class="col col-md-10" style="margin-bottom: 15px;">
                <h2>Listado de Semillas:</h2>
                <a class="botoncito" href="{% url 'inventario:stock_ingresar' %}" target="_blank">
                    Ingresar al Stock
                   <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Ingresar">
                </a><br>
                <a class="btn btn-primary btn-sm float-right" href="{% url 'inventario:menu_semillas' %}">Volver al Menú</a>
            </div>
            <div class="col col-md-2 ref">
                <h5>Referencias:</h5>
                <p style="font-size: 80%;"><img class="icons" src="{% static '/img/icons/lupa.png' %}" style="width: 10%;">   Detalles
                <img class="icons" src="{% static '/img/icons/germinacion.png' %}" style="width: 10%;">   Germinar</p>
                <p style="font-size: 80%;"><img class="icons" src="/static/admin/img/icon-changelink.svg" style="width: 10%;">   Editar
                <img class="icons" src="/static/admin/img/icon-deletelink.svg" style="width: 10%;">   baja</p>
            </div>
        </div>
        <div class="row">
        <div class="col-md-12">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Variedad</th>
                        <th>Código de Paquete</th>
                        <th>Cant. de Semillas</th>
                        <th>Peso en Gramos</th>
                        <th>Peso Utilizado</th>
                        <th>Peso Disponible</th>
                        <th>SubUbicación</th>
                        <th>Tipo de Contenedor</th>
                        <th class="col-md-1">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in stock %}
                    {% if s.variedad.activo == True %}
                        <tr>
                            <td>{{s.variedad.raza}}</td>
                            <td>{{s.codigo}}</td>
                            <td>{{s.cant_semillas}}</td>
                            <td>{{s.peso}}</td>
                            <td>{{s.peso_utilizado}}</td>
                            <td>{% if s.peso_disponible > 0%}
                                <b style="color:green;">{{s.peso_disponible}}</b></td>
                            {% else %}
                                <b style="color:red;">{{s.peso_disponible}}</b></td>
                            {% endif %}
                            <td>{{s.sububicacion}}</td>
                            <td>{{s.contenedor}}</td>
                            <td>
                                <a href="{% url 'inventario:stock_detalles' stock_id=s.id %}" alt="Detalles">
                                    <img class="icons" src="{% static '/img/icons/lupa.png' %}" style="width: 20%">
                                </a>
                                <a href="{% url 'produccion:germinar' semilla_id=s.id %}" alt="Germinar">
                                    <img class="icons" src="{% static '/img/icons/germinacion.png' %}" style="width: 20%">
                                </a>
                                <a class="nolink" href="{% url 'inventario:stock_mod' stock_id=s.id %}">
                                    <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar" style="width: 22%">
                                </a>
                                <a class="nolink" href="{% url 'inventario:stock_baja' stock_id=s.id %}">
                                    <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Baja" style="width: 22%">
                                </a>
                            </td>
                        </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}