cannavase/cannavase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
#Imports Extras
import debug_toolbar
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),
    
    #Admin-User Paths
    # url(r'^login/$',auth_views.LoginView.as_view(template_name="utils/login.html"), name="login"),
    # url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    #path('novedades/', include('novedades.urls')),
    path('noticias/', include('noticias.urls')),

    #SISTEMA
    path('operadores/', include('operadores.urls')),
    path('georef/', include('georef.urls')),
    path('inventario/', include('inventario.urls')),
    path('produccion/', include('produccion.urls')),
    path('comercial/', include('comercial.urls')),
    path('reportes/', include('reportes.urls')),
    # path('laboratorio/', include('laboratorio.urls')),
    path('cultivo/', include('cultivo.urls')),

    #API
    path('api/', include('georef.urlsAPI')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cannavase/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete
#Definimos nuestros Paths

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('cooperamos', views.cooperamos, name='cooperamos'),
    path('hacemos', views.hacemos, name='hacemos'),
    path('somos', views.somos, name='somos'),
    path('contactos', views.contactos, name='contactos'),

    path('menu', views.menu, name='menu'),

    path('mostrar', views.mostrar, name='mostrar'),

    path('menu_opciones', views.menu_opciones, name='menu_opciones'),
    path('alianzas', views.lista_alianzas, name='lista_alianzas'),
    path('alianzas/crear', views.cargar_alianza, name='crear_alianza'),
    path('alianzas/mod/<int:alianza_id>', views.cargar_alianza, name='modificar_alianza'),
    path('alianzas/del/<int:alianza_id>', views.desactivar_alianza, name='desactivar_alianza'),
    path('directivos', views.lista_directivos, name='lista_directivos'),
    path('directivos/crear', views.cargar_directivo, name='crear_directivo'),
    path('directivos/mod/<int:directivo_id>', views.cargar_directivo, name='modificar_directivo'),
    path('directivos/del/<int:directivo_id>', views.desactivar_directivo, name='desactivar_directivo'),
    path('videos', views.lista_videos, name='lista_videos'),
    path('videos/crear', views.cargar_video, name='cargar_video'),
    path('videos/mod/<int:video_id>', views.cargar_video, name='modificar_video'),
    path('videos/del/<int:video_id>', views.desactivar_video, name='desactivar_video'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    path('construccion', views.construccion, name='construccion'),
]

cannavase/noticias/urls.py
from django.urls import path
#Import de modulos personales
from . import views

app_name = 'noticias'
urlpatterns = [
    path('public', views.ver_noticias, name='ver_noticias'),
    path('public/<int:noticia_id>', views.ver_noticia, name='ver_noticia'),

    #Utilidades
    path('public/buscar', views.buscar_noticias, name='buscar_noticias'),
    path('public/tags/<int:tag_id>', views.buscar_etiqueta, name='buscar_etiqueta'),

    #Administracion
    path('', views.menu, name='menu_comunicaciones'),
    path('lista', views.lista_noticias, name='lista_noticias'),
    path('crear', views.crear_noticias, name='crear_noticias'),
    path('mod/<int:noticia_id>', views.crear_noticias, name='mod_noticias'),
    path('del/<int:noticia_id>', views.delete_noticias, name='delete_noticias'),
]

cannavase/core/forms.py
#Imports Python
from datetime import date
#Imports Django
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
#Imports extra
from dal import autocomplete
from tinymce.widgets import TinyMCE
#Imports del proyecto
from cannavase.settings import SECRET_KEY
#Imports de la app
from .models import Alianza, Director, Video
from .widgets import XDSoftDatePickerInput, XDSoftDateTimePickerInput

#Definimos nuestros formularios
class SearchForm(forms.Form):
    search = forms.CharField(label="", required=True)

class FileForm(forms.Form):
    archivo = forms.FileField()

class UploadCsv(forms.Form):
    csvfile = forms.FileField(widget=forms.FileInput(attrs={'accept': ".csv"}))

class UploadFoto(forms.Form):
    imagen = forms.FileField()

class TextoForm(forms.Form):
    texto = forms.CharField(initial='+549388')

class ChangeEmailForm(forms.Form):
    email = forms.EmailField(label='Email')

class UploadCsvWithPass(forms.Form):
    csvfile = forms.FileField(label="Archivo CSV Masivo", widget=forms.FileInput(attrs={'accept': ".csv"}))
    passwd = forms.CharField(label="Password de Administrador", max_length=100, widget=forms.PasswordInput)
    def clean(self):
        if self.cleaned_data['passwd'] == SECRET_KEY:
            return self.cleaned_data
        else:
            raise forms.ValidationError("La contraseña ingresada es incorrecta.")

class UploadDobleCsvWithPass(forms.Form):
    csvfile1 = forms.FileField(label="Archivo CSV Masivo", widget=forms.FileInput(attrs={'accept': ".csv"}))
    csvfile2 = forms.FileField(label="Archivo CSV Secundario", widget=forms.FileInput(attrs={'accept': ".csv"}))
    passwd = forms.CharField(label="Password de Administrador", max_length=100, widget=forms.PasswordInput)
    def clean(self):
        if self.cleaned_data['passwd'] == SECRET_KEY:
            return self.cleaned_data
        else:
            raise forms.ValidationError("La contraseña ingresada es incorrecta.")

class MesForm(forms.Form):
    month = forms.ChoiceField(label='Periodo', choices=[(m,m) for m in range(1,13)], initial=timezone.now().month)
    year = forms.ChoiceField(label='Año', choices=[(y,y) for y in range(2020, timezone.now().year+1)], initial=timezone.now().year)
    def __init__(self, *args, **kwargs):
        self.alinear = [('month', 'year'), ]
        super(MesForm, self).__init__(*args, **kwargs)

class FechaForm(forms.Form):
    fecha = forms.DateField(initial=date.today(), widget=forms.SelectDateWidget())

class PeriodoForm(forms.Form):
    begda = forms.DateField(label='Inicio', initial=timezone.now(), widget=XDSoftDatePickerInput(attrs={'autocomplete':'off'}))
    endda = forms.DateField(label='Fin', initial=timezone.now(), widget=XDSoftDatePickerInput(attrs={'autocomplete':'off'}))
    def clean(self):
        if self.cleaned_data['begda'] > self.cleaned_data['endda']:
            raise forms.ValidationError("La fecha de Inicio debe ser Menor a la de fin.")
        self.begda = self.cleaned_data['begda']
        self.endda = self.cleaned_data['endda']
        return self.cleaned_data

class AuditoriaForm(forms.Form):
    usuario = forms.ModelChoiceField(
        label='Usuario',
        queryset=User.objects.all(),
        widget=autocomplete.ModelSelect2(url='core:usuarios-autocomplete'),
        required=True)
    begda = forms.DateField(label='Inicio', initial=timezone.now(), widget=XDSoftDatePickerInput(attrs={'autocomplete':'off'}))
    endda = forms.DateField(label='Fin', initial=timezone.now(), widget=XDSoftDatePickerInput(attrs={'autocomplete':'off'}))
    def __init__(self, *args, **kwargs):
        super(AuditoriaForm, self).__init__(*args, **kwargs)
        if kwargs.get('initial', None):
            if kwargs['initial'].get('usuario'):
                self.fields['usuario'].widget = forms.HiddenInput()
    def clean(self):
        if self.cleaned_data['begda'] > self.cleaned_data['endda']:
            raise forms.ValidationError("La fecha de Inicio debe ser Menor a la de fin.")
        if self.cleaned_data['endda'] > date.today():
            raise forms.ValidationError("No puede ingresar una fecha posteriores a hoy.")
        return self.cleaned_data

class EmailForm(forms.Form):
    destinatario = forms.EmailField(label='Correo Destinatario', required=True)
    asunto = forms.CharField(label="Asunto", required=True)
    cuerpo = forms.CharField(label="Cuerpo", widget=forms.Textarea(), required=True)
    def __init__(self, *args, **kwargs):
        super(EmailForm, self).__init__(*args, **kwargs)
        if kwargs.get('initial', None):
            self.fields['destinatario'].widget.attrs['readonly'] = True

class JustificarForm(forms.Form):
    justificacion = forms.CharField(widget=forms.Textarea())


class AlianzaForm(forms.ModelForm):
    class Meta:
        model = Alianza
        fields = '__all__'


class DirectivoForm(forms.ModelForm):
    class Meta:
        model = Director
        fields = '__all__'


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = '__all__'

cannavase/core/views.py
#Imports Django
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import permission_required
#Imports del proyecto
from noticias.models import Noticia, Foto
from noticias.forms import HomeForm
#Imports de la app
from .apps import CoreConfig
from .choices import TIPO_ALIANZA, NACIONALIDADES
from .models import Video, Alianza, Director, Home
from .functions import get_home_config
from .forms import AlianzaForm, DirectivoForm, VideoForm

# Create your views here.

def home(request):
    video = Video.objects.filter(actual=True).order_by('-fecha').first()
    alianzas = Alianza.objects.filter(activa=True)
    noticias = Noticia.objects.all().filter(destacada=True).order_by("-fecha")[:3]
    return render(request, 'home.html', {
        'video':video,
        'alianzas': alianzas,
        'noticias': noticias,
        'mostrar': get_home_config(),
        }
    )

def cooperamos(request):
    mostrar = Home.objects.last()
    return render(request, 'cooperamos.html', {
        'mostrar': get_home_config(),
        }
    )

def hacemos(request):
    mostrar = Home.objects.last()
    return render(request, 'hacemos.html', {
        'mostrar': get_home_config(),
        }
    )

def somos(request):
    mostrar = Home.objects.get(id=1)
    categorias = []
    for tipo in TIPO_ALIANZA:
        if Alianza.objects.filter(tipo=tipo[0], activa=True).exists():
            categorias.append(tipo)
    alianzas = Alianza.objects.filter(activa=True)
    directores = Director.objects.filter(activo=True).order_by('orden')
    return render(request, 'somos.html', {
        'mostrar': mostrar,
        'alianzas': alianzas,
        'categorias': categorias,
        'directores': directores
        }
    )

def contactos(request):
    mostrar = Home.objects.get(id=1)
    return render(request, 'contactos.html', {'mostrar':mostrar})

#PRIVADO
@staff_member_required
def menu(request):
    return render(request, 'menu_principal.html', {
        'opciones': CoreConfig.ADMIN_MENU,
    })

@permission_required('operadores.wservices')
def mostrar(request):
    mostrar = get_home_config()
    form = HomeForm(instance=mostrar)
    if request.method == 'POST':
        form = HomeForm(request.POST, instance=mostrar)
        if form.is_valid():
            form.save()
            return redirect('noticias:menu_comunicaciones')
    return render(request, "extras/generic_form.html", {
        'titulo': "Opciones del Home",
        'form': form,
        'boton': "Guardar",
        }
    )

@permission_required('operadores.wservices')
def menu_opciones(request):
    return render(request, 'opciones/menu_opciones.html', {})

@permission_required('operadores.wservices')
def lista_alianzas(request):
    alianzas = Alianza.objects.all()
    for i in alianzas:
        for j in NACIONALIDADES:
            if i.nacionalidad == j[0]:
                i.nacionalidad = j[1]
    return render(request, 'opciones/lista_alianzas.html', {
        'alianzas':alianzas,
        'has_table': True,
        })

@permission_required('operadores.wservice')
def cargar_alianza(request, alianza_id=None):
    if alianza_id:
        alianza = Alianza.objects.get(pk=alianza_id)
        form = AlianzaForm(instance=alianza)
        if request.method == "POST":
            form = AlianzaForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('core:lista_alianzas')
    else:
        form = AlianzaForm()
        if request.method == "POST":
            form = AlianzaForm(request.POST, request.FILES, instance=alianza)
            if form.is_valid():
                form.save()
                return redirect('core:lista_alianzas')
    return render(request, "extras/generic_form.html",
                  {'titulo': "Crear Nueva Alianza", 'form': form, 'boton': "Agregar", })

def desactivar_alianza(request, alianza_id):
    alianza = Alianza.objects.get(pk=alianza_id)
    if alianza.activa:
        alianza.activa = False
    else:
        alianza.activa = True
    alianza.save()
    return redirect('core:lista_alianzas')


@permission_required('operadores.wservices')
def lista_directivos(request):
    directivos = Director.objects.all()
    return render(request, 'opciones/lista_directivos.html', {'directivos':directivos})

@permission_required('operadores.wservice')
def cargar_directivo(request, directivo_id=None):
    if directivo_id:
        directivo = Director.objects.get(pk=directivo_id)
        form = DirectivoForm(instance=directivo)
        if request.method == "POST":
            form = DirectivoForm(request.POST, request.FILES, instance=directivo)
            if form.is_valid():
                form.save()
                return redirect('core:lista_directivos')
    else:
        form = DirectivoForm()
        if request.method == "POST":
            form = DirectivoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('core:lista_directivos')
    return render(request, "extras/generic_form.html",
                  {'titulo': "Cargar Nuevo Directivo", 'form': form, 'boton': "Guardar", })

def desactivar_directivo(request, directivo_id):
    directivo = Director.objects.get(pk=directivo_id)
    if directivo.activo:
        directivo.activo = False
    else:
        directivo.activo = True
    directivo.save()
    return redirect('core:lista_directivos')


@permission_required('operadores.wservices')
def lista_videos(request):
    videos = Video.objects.all()
    return render(request, 'opciones/lista_videos.html', {'videos':videos})

@permission_required('operadores.wservice')
def cargar_video(request, video_id=None):
    if video_id:
        video = Video.objects.get(pk=video_id)
        form = VideoForm(instance=video)
        if request.method == "POST":
            form = VideoForm(request.POST, request.FILES, instance=video)
            if form.is_valid():
                form.save()
                return redirect('core:lista_videos')
    else:
        form = VideoForm()
        if request.method == "POST":
            form = VideoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('core:lista_videos')
    return render(request, "extras/generic_form.html",
                  {'titulo': "Cargar Nuevo Video", 'form': form, 'boton': "Guardar", })

def desactivar_video(request, video_id):
    video = Video.objects.get(pk=video_id)
    if video.actual:
        video.actual = False
    else:
        video.actual = True
    video.save()
    return redirect('core:lista_videos')


#Activar mails
def activar_usuario_mail(request, usuario_id, token):
    try:
        usuario = User.objects.get(pk=usuario_id)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        usuario = None
    if usuario and account_activation_token.check_token(usuario, token):
        usuario.is_active = True
        usuario.save()
        texto = 'Excelente! Su correo electronico fue validada.'
    else:
        texto = 'El link de activacion es invalido!'
    return render(request, 'extras/resultado.html', {'texto': texto, })

def construccion(request):
    return render(request, 'extras/construccion.html', {})

cannavase/core/templates/opciones/lista_alianzas.html
{% extends 'base_inventario.html' %}

{% load static %}

{% block body_block %}
{#<style>#}
{#    .ref {#}
{#        border-top-width: 3px;#}
{#        border-right-width: 3px;#}
{#        border-bottom-width: 3px;#}
{#        border-left-width: 3px;#}
{#        border-top-style: dotted;#}
{#        border-right-style: dotted;#}
{#        border-bottom-style: dotted;#}
{#        border-left-style: dotted;#}
{#        border-top-color: green;#}
{#        border-right-color: green;#}
{#        border-bottom-color: green;#}
{#        border-left-color: green;#}
{#    }#}
{#</style>#}
    <div class="beneficiario container">
        <div class="row">
            <div class="col col-md-10" style="margin-bottom: 15px;">
                <h2>Listado de Alianzas</h2>
                    <a class="btn btn-primary btn-sm" href="{% url 'noticias:menu_comunicaciones' %}">Volver al Menú Anterior</a>
            <br><br>
            </div>
{#            <div class="col col-md-2 ref">#}
{#                <h5>Referencias:</h5>#}
{#                <p style="font-size: 80%;"><img class="icons" src="/static/admin/img/icon-changelink.svg" style="width: 10%;">   Editar#}
{#                </p>#}
{#                <p style="font-size: 80%;"><img class="icons" src="/static/img/icons/check.png" style="width: 10%;">   Activar#}
{#                <img class="icons" src="/static/admin/img/icon-deletelink.svg" style="width: 10%;">   Desactivar</p>#}
{#            </div>#}
        </div>
        <div class="row">
        <div class="col-md-12">
                    <a class="botoncito" href="{% url 'core:crear_alianza' %}">
                        Crear Alianza
                        <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
                    </a><br>
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Orden</th>
                        <th>Nacionalidad</th>
                        <th>Logo</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% if alianzas %}
                    {% for alianza in alianzas %}
                        <tr>
                            <td>{{alianza.nombre}}</td>
                            <td>{{alianza.tipo}}</td>
                            <td>{{alianza.orden}}</td>
                            <td>{{alianza.nacionalidad}}</td>
                            <td>{{alianza.logo}}</td>
                            <td><!-- Icono de Activo -->
                                {% if alianza.activa == True %}
                                    <b style="color:green;">Activo</b>
                                {% else %}
                                    <b style="color:red;">Inactivo</b>
                                {% endif %}
                            </td>
                            <td>
                                <a title="Modificar" class="nolink" href="{% url 'core:modificar_alianza' alianza_id=alianza.id %}">
                                    <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                </a>
                                {% if alianza.activa == True %}
                                <a title="Desactivar" class="nolink" href="{% url 'core:desactivar_alianza' alianza_id=alianza.id %}">
                                    <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                </a>
                                {% else %}
                                <a title="Activar" class="nolink" href="{% url 'core:desactivar_alianza' alianza_id=alianza.id %}">
                                    <img class="icons" src="/static/img/icons/check.png" alt="Activar">
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                <h1>No hay registros</h1>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
        </br></br>
            <p>Si desea eliminar una Alianza, comuníquese con el Administrador</p>
{% endblock %}

cannavase/core/templates/opciones/lista_directivos.html
{% extends 'base_inventario.html' %}

{% load static %}

{% block body_block %}
{#<style>#}
{#    .ref {#}
{#        border-top-width: 3px;#}
{#        border-right-width: 3px;#}
{#        border-bottom-width: 3px;#}
{#        border-left-width: 3px;#}
{#        border-top-style: dotted;#}
{#        border-right-style: dotted;#}
{#        border-bottom-style: dotted;#}
{#        border-left-style: dotted;#}
{#        border-top-color: green;#}
{#        border-right-color: green;#}
{#        border-bottom-color: green;#}
{#        border-left-color: green;#}
{#    }#}
{#</style>#}
    <div class="beneficiario container">
        <div class="row">
            <div class="col col-md-10" style="margin-bottom: 15px;">
                <h2>Listado de Directivos</h2>
                    <a class="btn btn-primary btn-sm" href="{% url 'noticias:menu_comunicaciones' %}">Volver al Menú Anterior</a>
            <br><br>
            </div>
{#            <div class="col col-md-2 ref">#}
{#                <h5>Referencias:</h5>#}
{#                <p style="font-size: 80%;"><img class="icons" src="/static/admin/img/icon-changelink.svg" style="width: 10%;">   Editar#}
{#                </p>#}
{#                <p style="font-size: 80%;"><img class="icons" src="/static/img/icons/check.png" style="width: 10%;">   Activar#}
{#                <img class="icons" src="/static/admin/img/icon-deletelink.svg" style="width: 10%;">   Desactivar</p>#}
{#            </div>#}
        </div>
        <div class="row">
        <div class="col-md-12">
        <a class="botoncito" href="{% url 'core:crear_directivo' %}">
                        Cargar Directivo
                        <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
                    </a><br>
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Foto</th>
                        <th>Orden</th>
                        <th>Título</th>
                        <th>Correo Electrónico</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% if directivos %}
                    {% for directivo in directivos %}
                        <tr>
                            <td>{{directivo.nombres}}</td>
                            <td>{{directivo.apellidos}}</td>
                            <td><img class="icons" src="/archivos/{{directivo.foto}}"></td>
                            <td>{{directivo.orden}}</td>
                            <td>{{directivo.cargo}}</td>
                            <td>{{directivo.email}}</td>
                            <td><!-- Icono de Activo -->
                                {% if directivo.activo == True %}
                                    <b style="color:green;">Activo</b>
                                {% else %}
                                    <b style="color:red;">Inactivo</b>
                                {% endif %}
                            </td>
                            <td>
                                <a title="Editar" class="nolink" href="{% url 'core:modificar_directivo' directivo_id=directivo.id %}">
                                    <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                </a>
                                {% if directivo.activo == True %}
                                <a title="Desactivar" class="nolink" href="{% url 'core:desactivar_directivo' directivo_id=directivo.id %}">
                                    <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                </a>
                                {% else %}
                                <a title="Activar" class="nolink" href="{% url 'core:desactivar_directivo' directivo_id=directivo.id %}">
                                    <img class="icons" src="/static/img/icons/check.png" alt="Activar">
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                <h1>No hay registros</h1>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
        </br></br>
            <p>Si desea eliminar un Directivo, comuníquese con el Administrador</p>
{% endblock %}

cannavase/core/templates/opciones/lista_videos.html
{% extends 'base_inventario.html' %}

{% load static %}

{% block body_block %}
{#<style>#}
{#    .ref {#}
{#        border-top-width: 3px;#}
{#        border-right-width: 3px;#}
{#        border-bottom-width: 3px;#}
{#        border-left-width: 3px;#}
{#        border-top-style: dotted;#}
{#        border-right-style: dotted;#}
{#        border-bottom-style: dotted;#}
{#        border-left-style: dotted;#}
{#        border-top-color: green;#}
{#        border-right-color: green;#}
{#        border-bottom-color: green;#}
{#        border-left-color: green;#}
{#    }#}
{#</style>#}
    <div class="beneficiario container">
        <div class="beneficiario container">
        <div class="row">
            <div class="col col-md-10" style="margin-bottom: 15px;">
                <h2>Listado de Videos</h2>
                    <a class="btn btn-primary btn-sm" href="{% url 'noticias:menu_comunicaciones' %}">Volver al Menú Anterior</a>
            </div>
{#            <div class="col col-md-2 ref">#}
{#                <h5>Referencias:</h5>#}
{#                <p style="font-size: 80%;"><img class="icons" src="/static/admin/img/icon-changelink.svg" style="width: 10%;">   Editar#}
{#                </p>#}
{#                <p style="font-size: 80%;"><img class="icons" src="/static/img/icons/check.png" style="width: 10%;">   Activar#}
{#                <img class="icons" src="/static/admin/img/icon-deletelink.svg" style="width: 10%;">   Desactivar</p>#}
{#            </div>#}
        </div>
        <div class="row">
        <div class="col-md-12">
        <a class="botoncito" href="{% url 'core:cargar_video' %}">
                        Cargar Video
                        <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
                    </a><br>
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descripción</th>
                        <th>Archivo</th>
                        <th>Actual?</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% if videos %}
                    {% for video in videos %}
                        <tr>
                            <td>{{video.titulo}}</td>
                            <td>{{video.descripcion}}</td>
                            <td>{{video.archivo}}</td>
                            <td><!-- Icono de Activo -->
                                {% if video.actual == True %}
                                    <b style="color:green;">Sí</b>
                                {% else %}
                                    <b style="color:red;">No</b>
                                {% endif %}
                            </td>
                            <td>
                                <a title="Editar" class="nolink" href="{% url 'core:modificar_video' video_id=video.id %}">
                                    <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                </a>
                                {% if video.actual == True %}
                                <a title="Desactivar" class="nolink" href="{% url 'core:desactivar_video' video_id=video.id %}">
                                    <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                </a>
                                {% else %}
                                <a title="Activar" class="nolink" href="{% url 'core:desactivar_video' video_id=video.id %}">
                                    <img class="icons" src="/static/img/icons/check.png" alt="Activar">
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                <h1>No hay registros</h1>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
        </br></br>
            <p>Si desea eliminar un Video, comuníquese con el Administrador</p>
{% endblock %}

cannavase/core/templates/opciones/menu_opciones.html
{% extends 'base_inventario.html' %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
            <h1>Menu Comunicaciones:</h1>
                <div class="row">
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            {% if perms.operadores.wservices %}
                                <li><a href="{% url 'noticias:lista_noticias' %}">Noticias</a></li>
                                <li><a href="{% url 'core:mostrar' %}">Visualizar Comunicaciones</a></li>
                                <li><a href="{% url 'core:lista_alianzas' %}">Alianzas</a></li>
                                <li><a href="{% url 'core:lista_directivos' %}">Directivos</a></li>
                                <li><a href="{% url 'core:lista_videos' %}">Videos</a></li>
                            {% endif %}
                        </ul>
                    </div>
{#                    <div class="col-md-4">#}
{#                        {% include 'info_user.html' %}#}
{#                        <a class="btn btn-primary" href="{% url 'core:menu' %}">Volver al Menú Principal</a>#}
{#                    </div>#}
                </div>
            </div>
        </section>
    </section>
{% endblock %}