cannavase/cannavase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
#Imports Extras
import debug_toolbar
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),
    
    #Admin-User Paths
    # url(r'^login/$',auth_views.LoginView.as_view(template_name="utils/login.html"), name="login"),
    # url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    #path('novedades/', include('novedades.urls')),
    path('noticias/', include('noticias.urls')),

    #SISTEMA
    path('operadores/', include('operadores.urls')),
    path('georef/', include('georef.urls')),
    path('inventario/', include('inventario.urls')),
    path('produccion/', include('produccion.urls')),
    path('comercial/', include('comercial.urls')),
    path('reportes/', include('reportes.urls')),
    # path('laboratorio/', include('laboratorio.urls')),
    path('cultivo/', include('cultivo.urls')),

    #API
    path('api/', include('georef.urlsAPI')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cannavase/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete
#Definimos nuestros Paths

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('cooperamos', views.cooperamos, name='cooperamos'),
    path('hacemos', views.hacemos, name='hacemos'),
    path('somos', views.somos, name='somos'),
    path('contactos', views.contactos, name='contactos'),

    path('menu', views.menu, name='menu'),

    path('mostrar', views.mostrar, name='mostrar'),

    path('menu_opciones', views.menu_opciones, name='menu_opciones'),
    path('alianzas', views.lista_alianzas, name='lista_alianzas'),
    path('alianzas/crear', views.cargar_alianza, name='crear_alianza'),
    path('alianzas/mod/<int:alianza_id>', views.cargar_alianza, name='modificar_alianza'),
    path('alianzas/del/<int:alianza_id>', views.desactivar_alianza, name='desactivar_alianza'),
    path('directivos', views.lista_directivos, name='lista_directivos'),
    path('directivos/crear', views.cargar_directivo, name='crear_directivo'),
    path('directivos/mod/<int:directivo_id>', views.cargar_directivo, name='modificar_directivo'),
    path('directivos/del/<int:directivo_id>', views.desactivar_directivo, name='desactivar_directivo'),
    path('videos', views.lista_videos, name='lista_videos'),
    path('videos/crear', views.cargar_video, name='cargar_video'),
    path('videos/mod/<int:video_id>', views.cargar_video, name='modificar_video'),
    path('videos/del/<int:video_id>', views.desactivar_video, name='desactivar_video'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    path('construccion', views.construccion, name='construccion'),
]

cannavase/operadores/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views
from . import autocomplete

app_name = 'operadores'
urlpatterns = [
    path('', views.menu, name='menu'),
    #ABM Operadores
    path('listar/op', views.listar_operadores, name='listar_operadores'),
    path('crear/op', views.crear_operador, name='crear_operador'),
    path('modificar/op/<int:operador_id>', views.mod_operador, name='modificar_usuario'),
    path('chpass/op/<int:operador_id>', views.cambiar_password, name='cambiar_password'),
    path('desactivar/op/<int:operador_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('activar/op/<int:operador_id>', views.activar_usuario, name='activar_usuario'),
    path('credencial/op/<int:operador_id>', views.ver_credencial, name='ver_credencial'),
    path('imprimir', views.imprimir_tarjetas, name='imprimir_tarjetas'),
    #Auditoria
    path('auditoria', views.auditoria, name='auditoria'),
    path('auditoria/<int:user_id>', views.auditoria, name='auditoria_propia'),
    path('auditar/obj/<int:content_id>/<int:object_id>', views.auditar_cambios, name='auditar_cambios'),
    path('asistencia/<int:operador_id>', views.asistencia, name='asistencia'),
    #Asistencia
    path('presentes', views.listado_presentes, name='listado_presentes'),
    path('checkin', views.checkin, name='checkin'),
    path('ingreso/<int:operador_id>', views.ingreso, name='ingreso'),
    path('checkout/<int:operador_id>', views.checkout, name='checkout'),
    path('asistencia', views.registro_asistencia, name='registro_asistencia'),
    #Autocomplete
    url(r'^operadores-autocomplete/$', autocomplete.OperadoresAutocomplete.as_view(), name='operadores-autocomplete',),
]

cannavase/operadores/models.py
#Imports de python
import qrcode
#Realizamos imports de Django
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
#Imports de paquetes extras
from auditlog.registry import auditlog
from tinymce.models import HTMLField
#Imports del proyecto:
from cannavase.settings import MEDIA_ROOT, LOADDATA
from cannavase.constantes import NOIMAGE
from core.choices import TIPO_DOCUMENTOS
#improts de la app
from .choices import NIVELES_SEGURIDAD

# Create your models here.
class Operador(models.Model):
    nivel_acceso = models.CharField("Acceso de Seguridad", max_length=1, choices=NIVELES_SEGURIDAD, default='B')
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="operador")
    tipo_doc = models.IntegerField(choices=TIPO_DOCUMENTOS, default=2)
    num_doc = models.CharField('Numero de Documento', unique=True, max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres  = models.CharField('Nombres', max_length=100)
    email = models.EmailField('Correo Electronico')
    telefono = models.CharField('Telefono', max_length=20, default='+549388')
    fotografia = models.FileField('Fotografia', upload_to='operadores/', null=True, blank=True)
    qrpath = models.CharField('qrpath', max_length=100, null=True, blank=True)
    class Meta:
        verbose_name_plural = 'Operadores'
        ordering = ['apellidos', 'nombres']
        permissions = (
            #Operadores:
            ("operador_admin", "Administrar de Operadores."),
            #Georef
            ("georef_admin", "Administrar GeoRefs"),
            #Inventario
            ("inventario_admin", "Administrar Inventario"),
            #Produccion
            ("produccion", "Operador de Cultivo"),
            ("produccion_admin", "Encargado de Trazabilidad de Cultivo"),
            #Reportes
            ("reportes", "Puede Obtener Reportes"),
            #Wservices
            ("wservices", "WebServices del Sistema"),
            #Comunicacion:
            ("comunicacion", "Administrador de Comunicaciones"),
        )
    def __str__(self):
        return self.apellidos + ', ' + self.nombres
    def get_foto(self):
        if self.fotografia:
            return self.fotografia.url
        else:
            return NOIMAGE
    def get_qrimage(self):
        if self.qrpath:
            return self.qrpath
        else:
            path = MEDIA_ROOT + '/operadores/qrcode-'+ str(self.num_doc)
            img = qrcode.make(str(self.num_doc))
            img.save(path)
            relative_path = '/archivos/operadores/qrcode-'+ str(self.num_doc)
            self.qrpath = relative_path
            self.save()
            return self.qrpath

if not LOADDATA:
    #Auditoria
    auditlog.register(Operador)
    auditlog.register(User)

cannavase/operadores/forms.py
#Imports Python
from datetime import date
#Imports Django
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxSelectMultiple
#Imports extra
from dal import autocomplete
#Imports del proyecto
from core.widgets import XDSoftDatePickerInput
#Imports de la app
from .models import Operador

#Definimos nuestros forms
class BuscarOperadorForm(forms.Form):
    operador = forms.ModelChoiceField(
        label='',
        queryset=Operador.objects.all(),
        widget=autocomplete.ModelSelect2(url='operadores:operadores-autocomplete')
    )

class CrearOperadorForm(forms.ModelForm):
    new_user = forms.BooleanField(label="Crear Usuario", initial=False, required=False)
    class Meta:
        model = Operador
        fields= '__all__'
        exclude = ('qrpath', 'usuario', 'individuo')

class ModOperadorForm(forms.ModelForm):
    username = forms.CharField(label='Usuario', max_length=15, min_length=6, required=False)
    permisos = forms.MultipleChoiceField(
        label='Permisos',
        widget=CheckboxSelectMultiple(attrs={'class':'multiplechoice',}),
        required=False,
    )
    class Meta:
        model = Operador
        fields= '__all__'
        exclude = ('qrpath', 'usuario', 'individuo')
    #Inicializacion
    def __init__(self, *args, **kwargs):
        #Obtenemos permisos
        permisos_list = kwargs.pop('permisos_list', None)
        if permisos_list:
            self.base_fields['permisos'].choices = [(p.id, p.name) for p in permisos_list]
        super(ModOperadorForm, self).__init__(*args, **kwargs)
    def clean_username(self):
        if not hasattr(self, 'instance') and User.objects.filter(username=self.cleaned_data['username']):
            raise forms.ValidationError("El usuario indicado ya esta en uso, si el usuario tiene mas de una funcion, contacte al administrador")
        return self.cleaned_data['username']
    def clean_email(self):
        if not hasattr(self, 'instance') and User.objects.filter(email=self.cleaned_data['email']):
            raise forms.ValidationError("El mail indicado ya esta en uso, si el usuario tiene mas de una funcion, contacte al administrador")
        return self.cleaned_data['email']

class ImprimirTarjetasForm(forms.Form):
    operadores = forms.MultipleChoiceField(
        label='Seleccione Operadores',
        choices=[],
        widget=CheckboxSelectMultiple(attrs={'class':'multiplechoice',}),
    )
    #Inicializacion
    def __init__(self, *args, **kwargs):
        #Obtenemos permisos
        self.base_fields['operadores'].choices = [(o.id, o.apellidos+', '+o.nombres ) for o in Operador.objects.all()]
        super(ImprimirTarjetasForm, self).__init__(*args, **kwargs)

class ModPassword(forms.Form):
    username = forms.CharField(label='Usuario', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    passwd1 = forms.CharField(label="Password", max_length=32, widget=forms.PasswordInput)
    passwd2 = forms.CharField(label="Repetir Password", max_length=32, widget=forms.PasswordInput)
    def clean_passwd2(self):
        passwd1 = self.cleaned_data['passwd1']
        passwd2 = self.cleaned_data['passwd2']
        if passwd1 != passwd2:
            raise forms.ValidationError("Las contraseñas no son iguales")
        return ''

class AuditoriaForm(forms.Form):
    usuario = forms.ModelChoiceField(
        label='Usuario',
        queryset=User.objects.all(),
        widget=autocomplete.ModelSelect2(url='core:usuarios-autocomplete'),
        required=True)
    begda = forms.DateField(label='Inicio', initial=timezone.now(), widget=XDSoftDatePickerInput())
    endda = forms.DateField(label='Fin',initial=timezone.now(), widget=XDSoftDatePickerInput())
    def __init__(self, *args, **kwargs):
        super(AuditoriaForm, self).__init__(*args, **kwargs)
        if kwargs.get('initial', None):
            if kwargs['initial'].get('usuario'):
                self.fields['usuario'].widget = forms.HiddenInput()

class AsistenciaForm(forms.Form):
    num_doc = forms.IntegerField(label='Num de Documento', required=False)
    widgets = {
        'num_doc': forms.TextInput(attrs={}),
    }
    def clean(self):
        #Buscamos si existe el operador
        try:           
            if self.cleaned_data['num_doc']:
                operador = Operador.objects.get(num_doc=self.cleaned_data['num_doc'])
        except Operador.DoesNotExist:
            raise forms.ValidationError('No existe Operador Autorizado con ese Documento de Identidad.')
        #Lo preparamos para futuro uso
        if operador:
            self.operador = operador
        return self.cleaned_data   

cannavase/operadores/templates/base_operadores.html
{% extends 'sistema/base.html' %}

{% load static %}

{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/operadores.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/inventario.css' %}" />
{% endblock %}

{% block body_block %}

{% endblock %}

{% block custom_script %}

{% endblock %}

cannavase/operadores/templates/info_user.html
{% load operadores_tags %}
{% block body_block %}
    <div class="info_user">
        {% ct_get_operador request as operador %}
        <p><b>{{operador.apellidos}}, {{operador.nombres}}</b></p>
        <p><b>D.N.I: </b>{{operador.num_doc}}</p>
{#        <p><b>Usuario:</b> {{request.user.username}}</b></p>#}
    </div>
{% endblock %}

cannavase/operadores/templates/ingreso_operador.html
{% extends 'base_operadores.html' %}

{% load adminusers_tags %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <div class="col-sm-7 tarjeta color-{{operador.nivel_acceso}}">
                        <div class="col-sm-8">
                            <h3 class="tipo">CANNABIS AVATARA SE</h3>
                            <hr>
                            <div class="informacion">
                                <p class="nums"><b>N° Documento:</b> {{operador.num_doc}}</p>
                                <p><b>Nombre y Apellido:</b></p>
                                <p class="tab">{{operador.usuario.last_name}}, {{operador.usuario.first_name}}</p>
                                <p><b>Nivel de Acceso:</b></p>
                                <p class="nums">{{operador.get_nivel_acceso_display}}</p>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="row recuadrofoto">
                                <img class="fotos" src="{{operador.get_foto}}">
                            </div>
                            <div class="row">
                                <img class="fotos" src="{{operador.get_qrimage}}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <ul class="menu_botones">
                            {% if perms.operadores.auditar_operadores %}
                                <li><a href="{% url 'operadores:checkin'  %}">Ingresar Otro Operador</a></li>
                                <li><a href="{% url 'operadores:listado_presentes'  %}">Listado de Operadores Presentes</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

cannavase/operadores/templates/lista_operadores.html
{% extends 'base_operadores.html' %}

{% load static %}

{% load adminusers_tags %}

{% block body_block %}
<style>
    .ref {
        border-top-width: 3px;
        border-right-width: 3px;
        border-bottom-width: 3px;
        border-left-width: 3px;
        border-top-style: dotted;
        border-right-style: dotted;
        border-bottom-style: dotted;
        border-left-style: dotted;
        border-top-color: green;
        border-right-color: green;
        border-bottom-color: green;
        border-left-color: green;
    }
</style>
    <section class="resumen">
        <section class="informacion_basica">
            <div class="beneficiario container">
                <div class="row">
                    <div class="col col-md-8" style="margin-bottom: 15px;">
                        <h1>Listado de Usuarios: <b>{{app_name}}</b></h1>
<!--                    <p style="float:right;">-->
<!--                        {% if perms.operadores.operadores %}-->
                            <a class="botoncito" href="{% url 'operadores:crear_operador' %}">
                                Crear Operador
                                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo Usuario">
                            </a><br>
                    <a class="btn btn-primary btn-sm float-right" href="{% url 'operadores:menu' %}">Volver al Menú Anterior</a>

<!--                        {% endif %}-->
<!--                    </p>-->
                    </div>
                    <div class="col col-md-4 ref">
                        <h5>Referencias:</h5>
                        <p style="font-size: 80%;">
                            <img class="icons" src="/static/img/icons/access_card.png" style="width: 7%;">   Ver Tarjeta
                            <img class="icons" src="/static/admin/img/icon-changelink.svg" style="width: 5%;">   Modificar
                            <img class="icons" src="/static/img/icons/changepassword.png" style="width: 5%;">   Cambiar Contraseña
                            <img class="icons" src="/static/img/icons/check.png" style="width: 5%;">   Activar
                        </p>
                        <p style="font-size: 80%;">
                            <img class="icons" src="/static/admin/img/icon-deletelink.svg" style="width: 5%;">   Desactivar
                            <img class="icons" src="/static/img/icons/audit.png" style="width: 5%;">   Auditar
                            <img class="icons" src="/static/img/icons/calendar.png" style="width: 5%;">   Ver Asistencia
                        </p>
                    </div>
                </div> 
                <div class="row"> 
                    <div class="col-md-12">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th>Num Documento</th>
                                    <th>Operador</th>
                                    <th>Nivel Autorizacion</th>
                                    <th>Telefono</th>
                                    <th>Email</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for operador in operadores %}
                                    <tr class="fila_usuario">
                                        
                                        <td>{{operador.usuario.username}}</td>
                                        <td>{{operador.num_doc}}</td>
                                        <td>
                                            {{operador.apellidos}}, {{operador.nombres}}
                                            {% if operador.individuo %}
                                                <a href="{% url 'informacion:ver_individuo' individuo_id=operador.individuo.id %}" target="_blank">
                                                    <img class="icons" src="/static/img/icons/check.png" alt="Ver">
                                                </a>
                                            {% endif %}
                                        </td>
                                        <td>{{operador.get_nivel_acceso_display}}</td>
                                        <td>{{operador.telefono}}</td>
                                        <td>{{operador.email}}</td>
                                        <td><!-- Icono de Activo -->
                                            {% if operador.usuario.is_active %}
                                                <b style="color:green;">Activo</b>
                                            {% else %}
                                                <b style="color:red;">Inactivo</b>
                                            {% endif %}
                                        </td>
                                        <td><!-- Acciones -->
                                            <a class="nolink" href="{% url 'operadores:ver_credencial' operador_id=operador.id %}">
                                                <img class="icons" src="/static/img/icons/access_card.png" alt="Ver Tarjeta">
                                            </a>
                                            <a class="nolink" href="{% url 'operadores:modificar_usuario'  operador_id=operador.id %}">
                                                <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                            </a>
                                            {% if operador.usuario %}
                                                <a class="nolink" href="{% url 'operadores:cambiar_password' operador_id=operador.id %}">
                                                    <img class="icons" src="/static/img/icons/changepassword.png" alt="Cambiar contraseña">
                                                </a>
                                                {% if operador.usuario.is_active %}
                                                    <a class="nolink" href="{% url 'operadores:desactivar_usuario' operador_id=operador.id %}">
                                                        <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                                    </a>
                                                {% else %}
                                                    <a class="nolink" href="{% url 'operadores:activar_usuario' operador_id=operador.id %}">
                                                        <img class="icons" src="/static/img/icons/check.png" alt="Activar">
                                                    </a>
                                                {% endif %}
                                                {% if perms.operadores.auditar_operadores %}
                                                    <a href="{% url 'operadores:auditoria_propia' user_id=operador.usuario.id %}">
                                                        <img class="icons" src="/static/img/icons/audit.png" alt="Auditoria">
                                                    </a>
                                                {% endif %}
                                            {% endif %}
                                            <a href="{% url 'operadores:asistencia' operador_id=operador.id %}">
                                                <img class="icons" src="/static/img/icons/calendar.png" alt="Asistencia">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   

cannavase/operadores/templates/listar_presentes.html
{% extends 'base_operadores.html' %}

{% load adminusers_tags %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h1>Listado de Operadores:</h1>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Ingreso</th>
                                    <th>Documento</th>
                                    <th>Operador</th>
                                    <th>Nivel de Acceso</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for evento in presentes %}
                                    <tr>
                                        <td>{{evento.fecha|time}}</td>
                                        <td>{{evento.operador.num_doc}}</td>
                                        <td>{{evento.operador.apellidos}}, {{evento.operador.nombres}}</td>
                                        <td>{{evento.operador.get_nivel_acceso_display}}</td>
                                        <td>
                                            <a class="nolink" href="{% url 'operadores:ver_credencial' operador_id=evento.operador.id %}">
                                                <img class="icons" src="/static/img/icons/access_card.png" alt="Ver Tarjeta">
                                            </a>
                                            <a class="nolink" href="{% url 'operadores:checkout' operador_id=evento.operador.id %}">
                                                <img class="icons" src="/static/img/icons/logout.png" alt="Marcar Egreso">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-4">
                        <ul class="menu_botones">
                            {% if perms.operadores.auditar_operadores %}
                                <li><a href="{% url 'operadores:checkin'  %}">Ingreso Operador</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   

cannavase/operadores/templates/menu_operadores.html
{% extends 'base_operadores.html' %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
            <h1>Menu Operadores:</h1>
                <div class="row">
                    <div class="col-md-8">
                        <ul class="menu_botones">

                            {% if perms.operadores.operadores %}
                                <hr>
                                <li><a href="{% url 'operadores:crear_operador'  %}">Crear Operador</a></li>
                                <li><a href="{% url 'operadores:listar_operadores'  %}">Ver Listado de Operadores</a></li>
                                <li><a href="{% url 'operadores:imprimir_tarjetas'  %}">Imprimir Credenciales</a></li>
                            {% endif %}

                            {% if perms.operadores.auditar_operadores %}
                                <hr>
                                <li><a href="{% url 'operadores:checkin'  %}">Ingreso Operador</a></li>
                                <li><a href="{% url 'operadores:listado_presentes'  %}">Listado de Presentes</a></li>
                                <li><a href="{% url 'operadores:registro_asistencia'  %}">Registro de Asistencia</a></li>
                                <li><a href="{% url 'operadores:auditoria' %}">Ver Auditoria de Operadores</a></li>
                            {% else %}
                                <li><a href="{% url 'operadores:auditoria_propia' user_id=request.user.id %}">Ver Mis Acciones</a></li>
                            {% endif %}                   
                            
                            {% if request.user.is_superuser %}
                                <hr>
                                <li><a href="{% url 'operadores:menu' %}">Opcion del Administrador</a></li>
                            {% endif %}
                        </ul>
                    </div>
{#                    <div class="col-md-4">#}
{#                        {% include 'info_user.html' %}#}
{#                         <a class="btn btn-primary" href="{% url 'core:menu' %}">Volver al Menú Principal</a>#}
{#                    </div>#}
                </div>
            </div>
        </section>
    </section>
{% endblock %}

cannavase/operadores/templates/registro_asistencia.html
{% extends 'base_operadores.html' %}

{% load operadores_tags %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h1>Registro de Asistencia de Operadores:</h1>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Documento</th>
                                    <th>Operador</th>
                                    <th>Acceso</th>
                                    <th>Ingreso</th>
                                    <th>Egreso</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for asistente in asistentes %}
                                    <tr>
                                        <td>{{asistente.num_doc}}</td>
                                        <td>{{asistente.apellidos}}, {{asistente.nombres}}</td>
                                        <td>{{asistente.get_nivel_acceso_display}}</td>
                                        <td>{% ct_get_fecha asistente ingresos %}</td>
                                        <td>{% ct_get_fecha asistente egresos %}</td>
                                        <td>
                                            <a class="nolink" href="{% url 'operadores:ver_credencial' operador_id=asistente.id %}">
                                                <img class="icons" src="/static/img/icons/access_card.png" alt="Ver Tarjeta">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   