cannavase/cannavase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
#Imports Extras
import debug_toolbar
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),
    
    #Admin-User Paths
    # url(r'^login/$',auth_views.LoginView.as_view(template_name="utils/login.html"), name="login"),
    # url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    #path('novedades/', include('novedades.urls')),
    path('noticias/', include('noticias.urls')),

    #SISTEMA
    path('operadores/', include('operadores.urls')),
    path('georef/', include('georef.urls')),
    path('inventario/', include('inventario.urls')),
    path('produccion/', include('produccion.urls')),
    path('comercial/', include('comercial.urls')),
    path('reportes/', include('reportes.urls')),
    # path('laboratorio/', include('laboratorio.urls')),
    path('cultivo/', include('cultivo.urls')),

    #API
    path('api/', include('georef.urlsAPI')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cannavase/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete
#Definimos nuestros Paths

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('cooperamos', views.cooperamos, name='cooperamos'),
    path('hacemos', views.hacemos, name='hacemos'),
    path('somos', views.somos, name='somos'),
    path('contactos', views.contactos, name='contactos'),

    path('menu', views.menu, name='menu'),

    path('mostrar', views.mostrar, name='mostrar'),

    path('menu_opciones', views.menu_opciones, name='menu_opciones'),
    path('alianzas', views.lista_alianzas, name='lista_alianzas'),
    path('alianzas/crear', views.cargar_alianza, name='crear_alianza'),
    path('alianzas/mod/<int:alianza_id>', views.cargar_alianza, name='modificar_alianza'),
    path('alianzas/del/<int:alianza_id>', views.desactivar_alianza, name='desactivar_alianza'),
    path('directivos', views.lista_directivos, name='lista_directivos'),
    path('directivos/crear', views.cargar_directivo, name='crear_directivo'),
    path('directivos/mod/<int:directivo_id>', views.cargar_directivo, name='modificar_directivo'),
    path('directivos/del/<int:directivo_id>', views.desactivar_directivo, name='desactivar_directivo'),
    path('videos', views.lista_videos, name='lista_videos'),
    path('videos/crear', views.cargar_video, name='cargar_video'),
    path('videos/mod/<int:video_id>', views.cargar_video, name='modificar_video'),
    path('videos/del/<int:video_id>', views.desactivar_video, name='desactivar_video'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    path('construccion', views.construccion, name='construccion'),
]

cannavase/cultivo/urls.py
from django.conf.urls import url
from django.urls import path

from . import views, autocomplete

app_name = 'cultivo'
urlpatterns = [
    path('', views.menu, name='menu'),

    # Semillas
    path('semilla', views.SemillaList.as_view(), name='semillaList'),
    path('semilla/create', views.SemillaCreate.as_view(), name='semillaCreate'),
    path('semilla/update/<int:pk>', views.SemillaUpdate.as_view(), name='semillaUpdate'),
    path('semilla/delete/<int:pk>', views.SemillaDelete.as_view(), name='semillaDelete'),
    path('semilla/detail/<int:pk>', views.SemillaDetalle.as_view(), name='semillaDetalle'),

    # Lote de Semillas
    path('loteSemillas', views.LoteSemillasList.as_view(), name='loteSemillasList'),
    path('loteSemillas/create', views.LoteSemillasCreate.as_view(), name='loteSemillasCreate'),
    path('loteSemillas/update/<int:pk>', views.LoteSemillasUpdate.as_view(), name='loteSemillasUpdate'),
    path('loteSemillas/delete/<int:pk>', views.LoteSemillasDelete.as_view(), name='loteSemillasDelete'),
    path('loteSemillas/detail/<int:pk>', views.LoteSemillaDetalle.as_view(), name='loteSemillasDetalle'),

    # Lote de Germinacion
    path('loteGerminacion', views.LoteGerminacionList.as_view(), name='loteGerminacionList'),
    path('loteGerminacion/create/<int:pk>', views.LoteGerminacionCreate.as_view(), name='loteGerminacionCreate'),
    path('loteGerminacion/update/<int:pk>', views.LoteGerminacionUpdate.as_view(), name='loteGerminacionUpdate'),
    path('loteGerminacion/delete/<int:pk>', views.LoteGerminacionDelete.as_view(), name='loteGerminacionDelete'),
    path('loteGerminacion/detail/<int:pk>', views.LoteGerminacionDetalle.as_view(), name='loteGerminacionDetalle'),
    path('loteGerminacion/plantas/<int:pk>', views.PlantasLogradas.as_view(), name='plantasLogradas'),

    # Lote Vegetativo
    path('loteVegetativo', views.LoteVegetativoList.as_view(), name='loteVegetativoList'),
    path('loteVegetativo/create/<int:pk>', views.LoteVegetativoCreate.as_view(), name='loteVegetativoCreate'),
    path('loteVegetativo/update/<int:pk>', views.LoteVegetativoUpdate.as_view(), name='loteVegetativoUpdate'),
    path('loteVegetativo/delete/<int:pk>', views.LoteVegetativoDelete.as_view(), name='loteVegetativoDelete'),
    path('loteVegetativo/detail/<int:pk>', views.LoteVegetativoDetalle.as_view(), name='loteVegetativoDetalle'),

    # Lote de Floracion
    path('loteFloracion', views.LoteFloracionList.as_view(), name='loteFloracionList'),
    path('loteFloracion/create/<int:pk>', views.LoteFloracionCreate.as_view(), name='loteFloracionCreate'),
    path('loteFloracion/update/<int:pk>', views.LoteFloracionUpdate.as_view(), name='loteFloracionUpdate'),
    path('loteFloracion/delete/<int:pk>', views.LoteFloracionDelete.as_view(), name='loteFloracionDelete'),
    path('loteFloracion/detail/<int:pk>', views.LoteFloracionDetalle.as_view(), name='loteFloracionDetalle'),
    
    # Lote de Secado
    path('loteSecado', views.LoteSecadoList.as_view(), name='loteSecadoList'),
    path('loteSecado/create/<int:pk>', views.LoteSecadoCreate.as_view(), name='loteSecadoCreate'),
    path('loteSecado/update/<int:pk>', views.LoteSecadoUpdate.as_view(), name='loteSecadoUpdate'),
    path('loteSecado/delete/<int:pk>', views.LoteSecadoDelete.as_view(), name='loteSecadoDelete'),
    path('loteSecado/detail/<int:pk>', views.LoteSecadoDetalle.as_view(), name='loteSecadoDetalle'),
    path('loteSecado/trimming/<int:pk>', views.Trimming.as_view(), name='loteSecadoTrimming'),
    path('loteSecado/secado/<int:pk>', views.Secado.as_view(), name='loteSecadoSecado'),

    # Lote de Flores Deshidratadas
    path('loteMaterial', views.LoteMaterialList.as_view(), name='loteMaterialList'),
    path('loteMaterial/create/<int:pk>', views.LoteMaterialCreate.as_view(), name='loteMaterialCreate'),
    path('loteMaterial/update/<int:pk>', views.LoteMaterialUpdate.as_view(), name='loteMaterialUpdate'),
    path('loteMaterial/delete/<int:pk>', views.LoteMaterialDelete.as_view(), name='loteMaterialDelete'),
    path('loteMaterial/detail/<int:pk>', views.LoteMaterialDetalle.as_view(), name='loteMaterialDetalle'),

    # Destruccion Plantas
    path('loteDestruccion', views.DestruccionList.as_view(), name='destruccionList'),
    path('loteDestruccion/vegetativo/create/<int:pk>', views.DestruccionVegetativoCreate.as_view(), name='destruccionVegetativoCreate'),
    path('loteDestruccion/floracion/create/<int:pk>', views.DestruccionFloracionCreate.as_view(), name='destruccionFloracionCreate'),
    path('loteDestruccion/germinacion/create/<int:pk>', views.DestruccionGerminacionCreate.as_view(), name='destruccionGerminacionCreate'),

    # Lote de Plantas Madre
    path('loteMadre', views.LoteMadreList.as_view(), name='loteMadreList'),
    path('loteMadre/create/<int:pk>', views.LoteMadreCreate.as_view(), name='loteMadreCreate'),
    path('loteMadre/update/<int:pk>', views.LoteMadreUpdate.as_view(), name='loteMadreUpdate'),
    path('loteMadre/delete/<int:pk>', views.LoteMadreDelete.as_view(), name='loteMadreDelete'),
    path('loteMadre/detail/<int:pk>', views.LoteMadreDetalle.as_view(), name='loteMadreDetalle'),

#Autocomplete
    url(r'^semillas-autocomplete/$', autocomplete.SemillaAutocomplete.as_view(), name='semillas-autocomplete',),
    url(r'^loteSemillas-autocomplete/$', autocomplete.LoteSemillaAutocomplete.as_view(), name='loteSemillas-autocomplete',),
    url(r'^loteGerminacion-autocomplete/$', autocomplete.LoteGerminacionAutocomplete.as_view(), name='loteGerminacion-autocomplete',),
    url(r'^loteVegetativo-autocomplete/$', autocomplete.LoteVegetativoAutocomplete.as_view(), name='loteVegetativo-autocomplete',),
    url(r'^loteFloracion-autocomplete/$', autocomplete.LoteFloracionAutocomplete.as_view(), name='loteFloracion-autocomplete',),
    url(r'^loteSecado-autocomplete/$', autocomplete.LoteSecadoAutocomplete.as_view(), name='loteSecado-autocomplete',),
]

cannavase/inventario/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#imports extra
from dal import autocomplete
#Import de modulos personales
from . import views
from . import autocomplete

#Definimos los paths de la app
app_name = 'inventario'
urlpatterns = [
    path('', views.menu, name='menu'),
    #Rubro:
    path('crear/rubro', views.crear_rubro, name='crear_rubro'),
    path('mod/rubro/<int:rubro_id>', views.crear_rubro, name='mod_rubro'),
    #Basico Items
    path('lista', views.lista_items, name='lista_items'),
    path('ver/<int:item_id>', views.ver_item, name='ver_item'),
    path('crear', views.crear_item, name='crear_item'),
    path('mod/<int:item_id>', views.crear_item, name='mod_item'),
    path('clonar/<int:item_id>', views.clonar_item, name='clonar_item'),
    path('del/<int:item_id>', views.eliminar_item, name='eliminar_item'),
    #caracteristica
    path('crear/caracteristica/<int:item_id>', views.cargar_caracteristica, name='cargar_caracteristica'),
    path('mod/caracteristica/<int:caracteristica_id>', views.cargar_caracteristica, name='mod_caracteristica'),
    #eventos:
    path('crear/evento/<int:item_id>', views.crear_evento, name='crear_evento'),
    path('devolver/<int:evento_id>', views.devolver_item, name='devolver'),
    path('transferir/<int:item_id>', views.transferir_item, name='transferir_item'),
    path('del/evento/<int:evento_id>', views.del_evento, name='del_evento'),

    #Reportes
    path('stock_semillas', views.stock_semillas, name='stock_semillas'),

    #Semillas
    path('menu_semillas', views.menu_semillas, name='menu_semillas'),
    path('lista_semillas', views.lista_semillas, name='lista_semillas'),
    path('cargar_semillas', views.crear_semilla, name='cargar_semillas'),
    path('mod_semillas/<int:semilla_id>', views.cargar_semilla, name='mod_semillas'),
    path('detalle_semilla/<int:semilla_id>', views.detalle_semilla, name='detalle_semilla'),
    path('baja_semilla/<int:semilla_id>', views.baja_semilla, name='baja_semilla'),

    #Semillas (Almacenes)
    path('p/stock_semillas', views.p_stock_semillas, name='p_stock_semillas'),
    path('p/stock_ingresar', views.ingreso, name='p_stock_ingresar'),
    path('p/stock_detalles/<int:stock_id>', views.detalle_stock, name='p_stock_detalles'),
    path('p/stock_mod/<int:stock_id>', views.mod_stock, name='p_stock_mod'),
    path('p/stock_baja/<int:stock_id>', views.baja_stock, name='p_stock_baja'),

    #Autocomplete
    url(r'^rubros-autocomplete/$', autocomplete.RubrosAutocomplete.as_view(), name='rubros-autocomplete',),
    url(r'^items-autocomplete/$', autocomplete.ItemsAutocomplete.as_view(), name='items-autocomplete',),
]

cannavase/produccion/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#imports extra
from dal import autocomplete
#Import de modulos personales
from . import views
from . import autocomplete

#Definimos los paths de la app
app_name = 'produccion'
urlpatterns = [
    path('', views.menu, name='menu'),
    #Lotes:
    path('lista/<str:tipo>', views.lista_objetos, name='lista_objetos'),
    path('lista_germinacion/<str:tipo>', views.lista_germinacion, name='lista_germinacion'),
    path('lista_vegetacion/<str:tipo>', views.lista_vegetacion, name='lista_vegetacion'),
    path('lista_floracion/<str:tipo>', views.lista_floracion, name='lista_floracion'),
    path('lista_cosecha/<str:tipo>', views.lista_cosecha, name='lista_cosecha'),
    path('lista_finalizados/<str:tipo>', views.lista_finalizados, name='lista_finalizados'),
    path('ver/<int:objeto_id>', views.ver_objeto, name='ver_objeto'),
    path('mod/<int:objeto_id>', views.mod_objeto, name='mod_objeto'),
    #acciones
    path('germinar/<int:semilla_id>', views.germinar, name='germinar'),
    path('agregar/semillas/<int:objeto_id>', views.agregar_semillas, name='agregar_semillas'),
    path('aplicar/<int:objeto_id>', views.aplicar_insumo, name='aplicar_insumo'),
    path('regar/<int:objeto_id>', views.regar, name='regar'),
    path('evolucionar/<int:objeto_id>', views.evolucionar_objeto, name='evolucionar_objeto'),
    path('individualizar/<int:objeto_id>', views.individualizar, name='individualizar'),
    path('individualizar/<int:objeto_id>/ubicacion/<int:ubicacion_id>', views.individualizar, name='individualizar_ubicacion'),
    path('transplantar/<int:objeto_id>', views.trasplantar, name='trasplantar'),
    path('trasplantar/ubicacion/<int:ubicacion_id>', views.trasplantar_ubicacion, name='trasplantar_ubicacion'),
    path('eliminar/<int:objeto_id>', views.eliminar_objeto, name='eliminar_objeto'),
    path('eliminar/ubicacion/<int:ubicacion_id>', views.del_ubicacion, name='del_ubicacion'),
    path('eliminar/accion/<int:accion_id>', views.del_accion, name='del_accion'),
    #caracteristicas
    path('crear/caracteristica/<int:objeto_id>', views.cargar_caracteristica, name='cargar_caracteristica'),
    path('mod/caracteristica/<int:caracteristica_id>', views.cargar_caracteristica, name='mod_caracteristica'),
    #REPORTES
    path('rep/lotes/semb', views.lotes_sembrados, name='lotes_sembrados'),
    path('rep/lotes/veg', views.lotes_vegetativos, name='lotes_vegetativos'),
    path('rep/lotes/flo', views.lotes_floracion, name='lotes_floracion'),
    path('rep/lotes/sec', views.lotes_secado, name='lotes_secado'),
    path('rep/bajas', views.plantas_eliminadas, name='plantas_eliminadas'),
    #Autocompletes
    url(r'^lotes-autocomplete/$', autocomplete.LotesAutocomplete.as_view(), name='lotes-autocomplete',),
    url(r'^plantas-autocomplete/$', autocomplete.PlantasAutocomplete.as_view(), name='plantas-autocomplete',),
]

cannavase/reportes/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#imports extra
from dal import autocomplete
#Import de modulos personales
from . import views

#Definimos los paths de la app
app_name = 'reportes'
urlpatterns = [
    path('', views.menu, name='menu'),
    path('informe', views.Informe.as_view(), name='informe'),
    path('pdf', views.GenerarPDF.as_view(), name='pdf'),
]

cannavase/reportes/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone


class Fechas(models.Model):
    aux = models.CharField(max_length=1, default='a')
    fechaDesde = models.DateField('Fecha desde', default=datetime(2019, 1, 1).strftime('%Y-%m-%d'))
    fechaHasta = models.DateField('Fecha hasta', default=timezone.now().strftime('%Y-%m-%d'))

cannavase/reportes/forms.py
from datetime import datetime

from django.utils import timezone
from .models import Fechas
from django import forms
from core.widgets import XDSoftDatePickerInput


class InformeFechasForm(forms.ModelForm):
    class Meta:
        model = Fechas
        fields = '__all__'
        exclude = ['aux']
        widgets = {
            'fechaDesde': XDSoftDatePickerInput(attrs={'autocomplete': 'off'}),
            'fechaHasta': XDSoftDatePickerInput(attrs={'autocomplete': 'off'}),
        }

cannavase/reportes/templates/InformePDF.html
{% load static %}
{% if semillas > 0 %}
    {% include 'pdfLoteSemillas.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if germinacion > 0 %}
    {% include 'pdfLoteGerminacion.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if vegetacion > 0 %}
    {% include 'pdfLoteVegetativo.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if floracion > 0 %}
    {% include 'pdfLoteFloracion.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if madres > 0 %}
    {% include 'pdfLoteMadres.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if secado > 0 %}
    {% include 'pdfLoteSecado.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if material > 0 %}
    {% include 'pdfLoteMaterial.html' %}
    <div class="pagebreak"> </div>
{% endif %}
{% if destruccion > 0 %}
    {% include 'pdfLoteDestruccion.html' %}
{% endif %}

<style>
    .pagebreak {
        clear: both;
        page-break-after: always;
    }
</style>

cannavase/reportes/templates/basePDF.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load mathfilters %}
    <meta charset="UTF-8">
    <title>Informe</title>
</head>
<body>
    <div class="row">
        <div class="col-1">
            <img src="{% static 'img/membrete1.jpg' %}" alt="">
            <img src="{% static 'img/membrete2.jpg' %}" alt="" style="float: right;">
        </div>
    </div>

{% block semillas %}

{% endblock %}

{% block germinacion %}

{% endblock %}

{% block vegetacion %}

{% endblock %}

{% block floracion %}

{% endblock %}

{% block layout_style %}
<style>
    @page { size: A4 landscape; margin: 1cm; }
    body {
        font-family: Arial;
        font-size: 10pt;
    }
    .listado {
        width: 100%;
        border: black 2px solid;
        border-collapse: collapse;
        text-align: center;
        font-size: 8pt;
    }
    th {
        background-color: orange;
        border: black 2px solid;
        border-collapse: collapse;
        text-align: center;
        font-size: 8pt;
    }
    td {
        border: black 2px solid;
        border-collapse: collapse;
        text-align: center;
        font-size: 8pt;
    }
    .referencias {
        font-size: 10pt;
    }
</style>

{% endblock %}

</body>
</html>

cannavase/reportes/templates/base_reportes.html
{% extends 'sistema/base.html' %}

{% load static %}
{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reportes.css' %}" />
{% endblock %}

{% block body_block %}

{% endblock %}

{% block custom_script %}

{% endblock %}

cannavase/reportes/templates/informe.html
{% extends 'base_reportes.html' %}

{% load static %}

{% block body_block %}

    <div class="beneficiario container">
        <div class="row">
            <div class="col col-md-10" style="margin-bottom: 15px;">
            <h2>Generaci&oacute;n de informes</h2>
            <a class="btn btn-primary btn-sm" href="{% url 'cultivo:menu' %}">Volver al Menú Anterior</a>
            <br><br></div></div>
        <div class="row">
            <div class="col-9">
                <h4>Rango de fechas: </h4>
                 <form action="" method="post">
                    {% csrf_token %}
                        {{ form }}
                    <input class="btn btn-success" type="submit" value="Filtrar" />
                </form>
            </div>
            <div class="col-2 offset-1">
                 <a class="btn btn-info" type="button" href="{% url 'reportes:pdf' %}">Generar Informe</a>
            </div>
        </div>
        <div class="row">
        <div class="col-md-12">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Tipo de Lote</th>
                        <th>Ubicaci&oacute;n 1er nivel</th>
                        <th>Ubicaci&oacute;n 2do nivel</th>
                        <th>Recipiente</th>
                        <th>Estado</th>
                        <th>Fecha de Movimiento</th>
                        <th>Activo</th>
                    </tr>
                </thead>
                <tbody>
                      {% for lote in lotes %}
                          {% for i in lote %}
                        <tr>
                            <td>{{ i.codigo }}</td>
                            <td>{{ i.lote.tipo }}</td>
                            <td>{{ i.lote.predio }}</td>
                            <td>{{ i.lote.instalacion }}</td>
                            <td>{{ i.lote.recipiente }}</td>
                            <td>{{ i.lote.estado }}</td>
                            <td>{{ i.lote.fechaMovimiento }}</td>
                            <td><input type="checkbox" checked></td>
                        </tr>
                              {% endfor %}
                       {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

cannavase/reportes/templates/menu_reportes.html
{% extends 'base_reportes.html' %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <h1>Menu Reportes:</h1>
                <div class="row">
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            <li><a href="{% url 'inventario:stock_semillas' %}">Stock de Semillas</a></li>
                            <li><a href="{% url 'produccion:lotes_sembrados' %}">Lotes Sembrados</a></li>
                            <li><a href="{% url 'produccion:lotes_vegetativos' %}">Lotes Vegetativos</a></li>
                            <li><a href="{% url 'produccion:lotes_floracion' %}">Lotes de Floración</a></li>
                            <li><a href="{% url 'produccion:lotes_secado' %}">Lotes de Secado</a></li>
                            <li><a href="{% url 'produccion:plantas_eliminadas' %}">Plantas Eliminadas</a></li>
                        </ul>
                    </div>
{#                    <div class="col-md-4">#}
{#                        {% include 'info_user.html' %}#}
{#                        <a class="btn btn-primary" href="{% url 'core:menu' %}">Volver al Menú Principal</a>#}
{#                    </div>#}
                </div>
            </div>
        </section>
    </section>
{% endblock %}

cannavase/reportes/templates/pdfLoteDestruccion.html
{% extends 'basePDF.html' %}
{% load mathfilters %}
{% block germinacion %}
    <h4><u>Declaración Jurada de Destricci&oacute;n de Plantas {{ fechaDesde }} - {{ fecha }}</u></h4>
    <br />
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table class="listado">
                    <thead>
                        <tr>
                            <th>C&oacute;digo</th>
                            <th>Cod. De Lote Planta Destru&iacute;da</th>
                            <th>Tipo de Lote</th>
                            <th>Variedad</th>
                            <th>Nº de Plantas</th>
                            <th>Actualizado al</th>
                            <th>Observaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for i in destrucciones %}
                        {% for des in i %}
                            <tr>
                                <td>{{ des.codigo }}</td>
                                {% if des.loteG %}
                                    <td>{{ des.loteG.codigo }}</td>
                                    <td>{{ des.loteG.lote.tipo }}</td>
                                    <td>{{ des.loteG.loteSemilla.semilla.variedad }}</td>
                                {% endif %}
                                {% if des.loteV %}
                                    <td>{{ des.loteV.codigo }}</td>
                                    <td>{{ des.loteV.lote.tipo }}</td>
                                    <td>{{ des.loteV.loteGerminacion.loteSemilla.semilla.variedad }}</td>
                                {% endif %}
                                {% if des.loteF %}
                                    <td>{{ des.loteF.codigo }}</td>
                                    <td>{{ des.loteF.lote.tipo }}</td>
                                    <td>{{ des.loteF.loteVegetativo.loteGerminacionloteSemilla.semilla.variedad }}</td>
                                {% endif %}
                                <td>{{ des.cantidad }}</td>
                                <td>{{ des.fecha|date:"d/m/Y" }}</td>
                                <td>{{ des.observaciones }}</td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                          <tr style="background-color: #7aba7b">
                              <td colspan="4"><b>Totales:</b></td>
                              <td><b>{{ destruccionTotal }}</b></td>
                              <td colspan="2"><b></b></td>
                          </tr>
                    </tbody>
                </table>
            <br />
{#            <div class="referencias">#}
{#                <p><b>LPP-1-BB1</b><br />#}
{#                <b>LPP:</b> Lote de planta productiva; <b>1:</b> Número de lote; <b>BB1:</b> variedad;</p>#}
{#                <p><b>LPP-C-5-BB3</b><br />#}
{#                <b>LPP:</b> Lote de planta productiva; <b>C:</b> Campo; <b>1:</b> Número de lote; <b>BB1:</b> variedad;</p>#}
{#                <p><b>LP-1-BB1</b><br />#}
{#                <b>LP:</b> Lote de plantín; <b>1:</b> Número de lote; <b>BB1:</b> variedad;</p>#}
{#            </div>#}
            </div>
        </div>
    </div>
{% endblock %}